# Generated by Django 5.2.13 on 2026-04-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_match_away_logo_url_match_home_logo_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coachprofile',
            options={'verbose_name': 'murabbiy profili', 'verbose_name_plural': 'murabbiy profillari'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-match_date', '-match_time'], 'verbose_name': "o'yin", 'verbose_name_plural': "o'yinlar"},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['shirt_number', 'full_name'], 'verbose_name': 'futbolchi', 'verbose_name_plural': 'futbolchilar'},
        ),
        migrations.AlterModelOptions(
            name='playerstatistic',
            options={'verbose_name': 'futbolchi statistikasi', 'verbose_name_plural': 'futbolchi statistikasi'},
        ),
        migrations.AlterModelOptions(
            name='teamstatistic',
            options={'ordering': ['sort_order', 'title'], 'verbose_name': 'jamoa statistikasi', 'verbose_name_plural': 'jamoa statistikasi'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['training_date', 'start_time'], 'verbose_name': "mashg'ulot", 'verbose_name_plural': "mashg'ulotlar"},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'foydalanuvchi profili', 'verbose_name_plural': 'foydalanuvchi profillari'},
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Kelgusi'), ('live', 'Jonli'), ('played', 'Tugagan')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Ruscha'), ('en', 'Inglizcha')], default='uz', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('light', "Yorug'"), ('dark', "Qorong'i")], default='light', max_length=10),
        ),
    ]
