# Generated by Django 5.2.13 on 2026-05-07 13:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_coachprofile_options_alter_match_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_status', models.CharField(choices=[('Qatnashdi', 'Qatnashdi'), ('Kelmadi', 'Kelmadi'), ('Kechikdi', 'Kechikdi'), ('Uzrli sabab', 'Uzrli sabab')], default='Qatnashdi', max_length=20)),
                ('attended_minutes', models.PositiveIntegerField(default=90)),
                ('training_duration_minutes', models.PositiveIntegerField(default=90)),
                ('fatigue_level', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('activity_score', models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('injury_status', models.CharField(choices=[("Yo'q", "Yo'q"), ('Bor', 'Bor'), ('Tiklanmoqda', 'Tiklanmoqda')], default="Yo'q", max_length=20)),
                ('coach_note', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_attendance_records', to='core.player')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.training')),
            ],
            options={
                'verbose_name': "mashg'ulot davomadi",
                'verbose_name_plural': "mashg'ulot davomadi",
                'ordering': ['-training__training_date', 'player__shirt_number', 'player__full_name'],
                'constraints': [models.UniqueConstraint(fields=('training', 'player'), name='unique_training_player_attendance')],
            },
        ),
    ]
