# Generated by Django 5.2.13 on 2026-05-07 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trainingattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingattendance',
            name='activity_score',
            field=models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1, message="Faollik bahosi 1 dan 10 gacha bo'lishi kerak."), django.core.validators.MaxValueValidator(10, message="Faollik bahosi 1 dan 10 gacha bo'lishi kerak.")]),
        ),
        migrations.AlterField(
            model_name='trainingattendance',
            name='attended_minutes',
            field=models.PositiveIntegerField(default=90, validators=[django.core.validators.MinValueValidator(0, message="Qatnashgan daqiqa manfiy bo'lishi mumkin emas.")]),
        ),
        migrations.AlterField(
            model_name='trainingattendance',
            name='fatigue_level',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message="Charchoq darajasi 1 dan 5 gacha bo'lishi kerak."), django.core.validators.MaxValueValidator(5, message="Charchoq darajasi 1 dan 5 gacha bo'lishi kerak.")]),
        ),
        migrations.AlterField(
            model_name='trainingattendance',
            name='training_duration_minutes',
            field=models.PositiveIntegerField(default=90, validators=[django.core.validators.MinValueValidator(1, message="Mashg'ulot davomiyligi 1 daqiqadan kam bo'lmasligi kerak.")]),
        ),
    ]
