# Generated by Django 5.2.13 on 2026-05-18 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_match_corners_match_possession_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingattendance',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='body_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='heart_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(30, message="Yurak urishi kamida 30 bpm bo'lishi kerak."), django.core.validators.MaxValueValidator(240, message='Yurak urishi 240 bpm dan oshmasligi kerak.')]),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='measured_height',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='measured_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='oxygen_saturation',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50, message="Kislorod darajasi kamida 50% bo'lishi kerak."), django.core.validators.MaxValueValidator(100, message='Kislorod darajasi 100% dan oshmasligi kerak.')]),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='pain_level',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message="Og'riq darajasi 1 dan 10 gacha bo'lishi kerak."), django.core.validators.MaxValueValidator(10, message="Og'riq darajasi 1 dan 10 gacha bo'lishi kerak.")]),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='respiratory_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5, message="Nafas olish tezligi kamida 5 marta/min bo'lishi kerak."), django.core.validators.MaxValueValidator(80, message='Nafas olish tezligi 80 marta/min dan oshmasligi kerak.')]),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='sleep_quality',
            field=models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1, message="Uyqu sifati 1 dan 10 gacha bo'lishi kerak."), django.core.validators.MaxValueValidator(10, message="Uyqu sifati 1 dan 10 gacha bo'lishi kerak.")]),
        ),
        migrations.AlterField(
            model_name='trainingattendance',
            name='fatigue_level',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message="Charchoq darajasi 1 dan 10 gacha bo'lishi kerak."), django.core.validators.MaxValueValidator(10, message="Charchoq darajasi 1 dan 10 gacha bo'lishi kerak.")]),
        ),
    ]
