from django.urls import path

from .views import (
    DashboardView,
    PlayerCreateView,
    PlayerDeleteView,
    PlayerDetailView,
    PlayerListView,
    PlayerUpdateView,
    SettingsView,
    StatisticsView,
    TrainingAttendanceView,
    TrainingCreateView,
    TrainingDeleteView,
    TrainingListView,
    TrainingUpdateView,
    attendance_record_detail_api,
    attendance_records_api,
    player_attendance_api,
    players_attendance_stats_api,
    save_training_attendance_api,
    team_attendance_stats_api,
    training_attendance_api,
)

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("players/", PlayerListView.as_view(), name="player_list"),
    path("players/add/", PlayerCreateView.as_view(), name="player_add"),
    path("players/<int:pk>/", PlayerDetailView.as_view(), name="player_detail"),
    path("players/<int:pk>/edit/", PlayerUpdateView.as_view(), name="player_edit"),
    path("players/<int:pk>/delete/", PlayerDeleteView.as_view(), name="player_delete"),
    path("training/", TrainingListView.as_view(), name="training_list"),
    path("training/add/", TrainingCreateView.as_view(), name="training_add"),
    path("training/<int:pk>/edit/", TrainingUpdateView.as_view(), name="training_edit"),
    path("training/<int:pk>/delete/", TrainingDeleteView.as_view(), name="training_delete"),
    path("attendance/", TrainingAttendanceView.as_view(), name="training_attendance"),
    path("statistics/", StatisticsView.as_view(), name="statistics"),
    path("settings/", SettingsView.as_view(), name="settings"),
    path("api/attendance/", attendance_records_api, name="api_attendance_records"),
    path("api/attendance/<int:record_id>/", attendance_record_detail_api, name="api_attendance_record_detail"),
    path("api/attendance/training/<int:training_id>/", training_attendance_api, name="api_training_attendance"),
    path("api/attendance/training/<int:training_id>/save/", save_training_attendance_api, name="api_save_training_attendance"),
    path("api/attendance/player/<int:player_id>/", player_attendance_api, name="api_player_attendance"),
    path("api/attendance/stats/team/", team_attendance_stats_api, name="api_team_attendance_stats"),
    path("api/attendance/stats/players/", players_attendance_stats_api, name="api_players_attendance_stats"),
]
