# Generated by Django 4.2 on 2026-04-05 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_team', models.CharField(max_length=150)),
                ('away_team', models.CharField(max_length=150)),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('stadium', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('upcoming', 'Kelgusi'), ('live', 'Live'), ('played', 'Tugagan')], default='upcoming', max_length=20)),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('attendance', models.PositiveIntegerField(blank=True, null=True)),
                ('referee', models.CharField(blank=True, max_length=120)),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-match_date', '-match_time'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('shirt_number', models.PositiveIntegerField(default=1)),
                ('position', models.CharField(choices=[('forward', 'Hujumchi'), ('midfielder', 'Yarim himoyachi'), ('defender', 'Himoyachi'), ('goalkeeper', 'Darvozabon')], max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('nationality', models.CharField(max_length=80)),
                ('height', models.DecimalField(decimal_places=2, help_text='Metrlarda', max_digits=4)),
                ('weight', models.PositiveIntegerField(help_text='Kilogramm')),
                ('join_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('short_note', models.CharField(blank=True, max_length=180)),
            ],
            options={
                'ordering': ['shirt_number', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='TeamStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('metric_value', models.CharField(max_length=50)),
                ('accent', models.CharField(default='blue', max_length=20)),
                ('change_text', models.CharField(blank=True, max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('training_type', models.CharField(choices=[('tactics', 'Taktika'), ('fitness', 'Jismoniy'), ('recovery', 'Tiklanish'), ('technical', 'Texnik')], max_length=20)),
                ('training_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=150)),
                ('note', models.TextField(blank=True)),
                ('attendance_total', models.PositiveIntegerField(default=0)),
                ('attendance_present', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['training_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='core.player')),
            ],
            options={
                'verbose_name': 'Player statistic',
                'verbose_name_plural': 'Player statistics',
            },
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(default='Bosh murabbiy', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('club_name', models.CharField(default='CoachPro Academy', max_length=150)),
                ('experience_years', models.PositiveIntegerField(default=5)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
