# Generated by Django 5.2.12 on 2026-04-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_logo_url',
            field=models.URLField(blank=True),
        ),
    ]
