# Generated by Django 5.2.13 on 2026-05-18 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_populate_player_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='corners',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='possession_percent',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0, message="To'p nazorati 0 dan kam bo'lishi mumkin emas."), django.core.validators.MaxValueValidator(100, message="To'p nazorati 100 dan oshmasligi kerak.")]),
        ),
        migrations.AddField(
            model_name='match',
            name='red_cards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='shots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='shots_on_target',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='yellow_cards',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='activity_level',
            field=models.CharField(choices=[('low', 'Past'), ('medium', "O'rtacha"), ('high', 'Yuqori')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='discipline',
            field=models.CharField(choices=[('good', 'Yaxshi'), ('warning', 'Ogohlantirish'), ('problem', 'Muammo bor')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='injury_note',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='physical_condition',
            field=models.CharField(choices=[('excellent', "Zo'r"), ('good', 'Yaxshi'), ('average', "O'rtacha"), ('tired', 'Charchagan'), ('injured', 'Jarohatlangan')], default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingattendance',
            name='rating',
            field=models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1, message="Baho 1 dan 10 gacha bo'lishi kerak."), django.core.validators.MaxValueValidator(10, message="Baho 1 dan 10 gacha bo'lishi kerak.")]),
        ),
    ]
