from datetime import date, time

from django.db import migrations


COMPLETED_MATCHES = [
    {
        "home_team": "Bunyodkor",
        "away_team": "Lokomotiv",
        "match_date": date(2026, 4, 6),
        "match_time": time(18, 0),
        "stadium": "Bunyodkor stadioni",
        "status": "played",
        "home_score": 3,
        "away_score": 0,
        "attendance": 12100,
        "referee": "Akobirxo'ja Shukurullayev",
        "possession_percent": 58,
        "shots": 15,
        "shots_on_target": 8,
        "corners": 6,
        "yellow_cards": 1,
        "red_cards": 0,
        "note": "Jamoa pressing va tezkor hujumlarda ustunlik qildi.",
    },
    {
        "home_team": "Surxon",
        "away_team": "Bunyodkor",
        "match_date": date(2026, 4, 10),
        "match_time": time(19, 0),
        "stadium": "Surxon arena",
        "status": "played",
        "home_score": 2,
        "away_score": 1,
        "attendance": 9800,
        "referee": "Firdavs Norsafarov",
        "possession_percent": 47,
        "shots": 9,
        "shots_on_target": 3,
        "corners": 3,
        "yellow_cards": 4,
        "red_cards": 0,
        "note": "Safardagi mag'lubiyatdan keyin himoya xatolari tahlil qilindi.",
    },
    {
        "home_team": "Bunyodkor",
        "away_team": "Sog'diyona",
        "match_date": date(2026, 4, 15),
        "match_time": time(18, 30),
        "stadium": "Bunyodkor stadioni",
        "status": "played",
        "home_score": 2,
        "away_score": 2,
        "attendance": 13400,
        "referee": "Asker Najafaliyev",
        "possession_percent": 53,
        "shots": 12,
        "shots_on_target": 5,
        "corners": 5,
        "yellow_cards": 2,
        "red_cards": 0,
        "note": "Oxirgi daqiqalarda durang natija qayd etildi.",
    },
    {
        "home_team": "Qizilqum",
        "away_team": "Bunyodkor",
        "match_date": date(2026, 4, 20),
        "match_time": time(20, 0),
        "stadium": "Yoshlik sport majmuasi",
        "status": "played",
        "home_score": 0,
        "away_score": 2,
        "attendance": 7600,
        "referee": "Sherzod Qosimov",
        "possession_percent": 55,
        "shots": 14,
        "shots_on_target": 7,
        "corners": 7,
        "yellow_cards": 2,
        "red_cards": 0,
        "note": "Safarda ishonchli g'alaba.",
    },
    {
        "home_team": "Bunyodkor",
        "away_team": "Andijon",
        "match_date": date(2026, 4, 25),
        "match_time": time(18, 0),
        "stadium": "Bunyodkor stadioni",
        "status": "played",
        "home_score": 1,
        "away_score": 0,
        "attendance": 15100,
        "referee": "Dilmurod Sodiqov",
        "possession_percent": 57,
        "shots": 11,
        "shots_on_target": 4,
        "corners": 4,
        "yellow_cards": 1,
        "red_cards": 0,
        "note": "Minimal hisobdagi muhim g'alaba.",
    },
    {
        "home_team": "Dinamo",
        "away_team": "Bunyodkor",
        "match_date": date(2026, 5, 1),
        "match_time": time(19, 30),
        "stadium": "Dinamo stadioni",
        "status": "played",
        "home_score": 1,
        "away_score": 3,
        "attendance": 11200,
        "referee": "Jasur Muxtorov",
        "possession_percent": 52,
        "shots": 13,
        "shots_on_target": 6,
        "corners": 5,
        "yellow_cards": 3,
        "red_cards": 0,
        "note": "Ikkinchi bo'limda jamoa o'yin tempini oshirdi.",
    },
    {
        "home_team": "Bunyodkor",
        "away_team": "Metallurg",
        "match_date": date(2026, 5, 6),
        "match_time": time(18, 30),
        "stadium": "Bunyodkor stadioni",
        "status": "played",
        "home_score": 0,
        "away_score": 1,
        "attendance": 12600,
        "referee": "Timur To'xtasinov",
        "possession_percent": 61,
        "shots": 16,
        "shots_on_target": 5,
        "corners": 8,
        "yellow_cards": 2,
        "red_cards": 0,
        "note": "Ustunlik bo'lsa ham vaziyatlardan foydalanish yetishmadi.",
    },
    {
        "home_team": "Mash'al",
        "away_team": "Bunyodkor",
        "match_date": date(2026, 5, 12),
        "match_time": time(19, 0),
        "stadium": "Bahrom Vafoev stadioni",
        "status": "played",
        "home_score": 0,
        "away_score": 0,
        "attendance": 8400,
        "referee": "Aziz Asimov",
        "possession_percent": 50,
        "shots": 8,
        "shots_on_target": 2,
        "corners": 3,
        "yellow_cards": 2,
        "red_cards": 0,
        "note": "Himoyaviy o'yin va teng kurash.",
    },
    {
        "home_team": "Bunyodkor",
        "away_team": "Paxtakor",
        "match_date": date(2026, 5, 17),
        "match_time": time(19, 0),
        "stadium": "Bunyodkor stadioni",
        "status": "played",
        "home_score": 2,
        "away_score": 1,
        "attendance": 18500,
        "referee": "Ilgiz Tantashev",
        "possession_percent": 54,
        "shots": 13,
        "shots_on_target": 6,
        "corners": 5,
        "yellow_cards": 2,
        "red_cards": 0,
        "note": "Derbi o'yinida jamoa ikkinchi bo'limda ustunlikni saqlab qoldi.",
    },
    {
        "home_team": "Nasaf",
        "away_team": "Bunyodkor",
        "match_date": date(2026, 5, 21),
        "match_time": time(20, 0),
        "stadium": "Markaziy stadion, Qarshi",
        "status": "played",
        "home_score": 1,
        "away_score": 1,
        "attendance": 14200,
        "referee": "Rustam Lutfullin",
        "possession_percent": 49,
        "shots": 10,
        "shots_on_target": 4,
        "corners": 4,
        "yellow_cards": 3,
        "red_cards": 0,
        "note": "Safardagi muhim ochko.",
    },
]


def upsert_completed_matches(apps, schema_editor):
    Match = apps.get_model("core", "Match")
    for item in COMPLETED_MATCHES:
        lookup = {
            "home_team": item["home_team"],
            "away_team": item["away_team"],
            "match_date": item["match_date"],
            "match_time": item["match_time"],
        }
        Match.objects.update_or_create(defaults=item, **lookup)


def remove_added_completed_matches(apps, schema_editor):
    Match = apps.get_model("core", "Match")
    for item in COMPLETED_MATCHES[:8]:
        Match.objects.filter(
            home_team=item["home_team"],
            away_team=item["away_team"],
            match_date=item["match_date"],
            match_time=item["match_time"],
        ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_seed_project_matches"),
    ]

    operations = [
        migrations.RunPython(upsert_completed_matches, remove_added_completed_matches),
    ]
